version: 2
jobs:
  build: &build
    docker:
      - image: circleci/ruby:latest
    working_directory: /home/circleci/app
    steps:
      - checkout
      - run:
          name: Install gems
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop
      - run:
          name: YARDoc
          command: yardoc --fail-on-warning lib
      # see https://docs.codeclimate.com/docs/circle-ci-test-coverage-example
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: RSpec
          command: |
            ./cc-test-reporter before-build
            rspec
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
      - store_artifacts:
          path: coverage
          destination: coverage
  ruby-2.3:
    <<: *build
    docker:
      - image: circleci/ruby:2.3
  ruby-2.4:
    <<: *build
    docker:
      - image: circleci/ruby:2.4
  ruby-2.5:
    <<: *build
    docker:
      - image: circleci/ruby:2.5

workflows:
  version: 2
  build-using-multi-rubies:
    jobs:
      - ruby-2.3
      - ruby-2.4
      - ruby-2.5
